### ISSUE TITLE
Support to add refund details in payment object

### ISSUE THREAD

**Issue by JindalMohit** [ONDC-Official/ONDC-Protocol-Specs#36]
For scenarios where refund needs to be initiated, how to share the refund status, amount, refund method, etc?

**Comment by mahoriR** [comment]
@JindalMohit Agreed. This will be needed. Payment object needs to be updated to handle this as well. @BLR-0118

**Comment by BLR-0118** [comment]
Refund details can be added to the payment object (check /update contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit))
