### ISSUE TITLE
Need an attribute for specifiying items contains egg for F & B

### ISSUE THREAD

**Issue by VidyaGF** [ONDC-Official/ONDC-Protocol-Specs#49]
Currently we see attributes for specifying if the item is veg or non-veg. While there needs to be an attribute which mentions the item contains egg or not

**Comment by BLR-0118** [comment]
use Item.descriptor.symbol as documented in the spec [retail-hyperlocal.yaml](https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/tree/master/protocol-specifications/core/v0/api)

**Comment by VidyaGF** [comment]
What should be the value of  item.descriptor.symbol for items that contain egg ? We see currently "Veg" and "Non-Veg" as two values that can be assigned.

**Comment by BLR-0118** [comment]
As discussed & decided, there will be separate keys for veg, non-veg as defined in the API contract
